### ISSUE TITLE
assertion triggered after upgrading to ejabberd 17.x

### ISSUE THREAD

**Issue by darix** [cdidier/irssi-xmpp#21]
The subscription attribute can be optional if no subscription exists according to https://github.com/processone/ejabberd/issues/1590 .

it seems the assert should be changed to a normal if then?

https://github.com/cdidier/irssi-xmpp/blob/master/src/core/rosters.c#L276

**Comment by cdidier** [comment]
The first "if (..." should be changed to "if (subscription == NULL || .." to set the subscription to NONE.

**Comment by darix** [comment]
while we are at it could we also fix

15:43:51 -!- Irssi: critical Source ID 1 was not found when attempting 
to remove it

**Comment by cdidier** [comment]
Fixed with 2c5560286530e2b5fb2b5688198cc71c9270c1f8.
