### ISSUE TITLE
irssi: symbol lookup error: irssi: undefined symbol: g_malloc_n

### ISSUE THREAD

**Issue by Astrades** [cdidier/irssi-xmpp#23]
After installing the plugin, I get this after trying to start irssi. What's the problem and how do I fix it?
Ubuntu 16.04 btw.

**Comment by cdidier** [comment]
Strange because this function exists since glib2 2.24 according to https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html#g-malloc-n
