### ISSUE TITLE
"critical Source ID 1 was not found when attempting to remove it"

### ISSUE THREAD

**Issue by cdidier** [cdidier/irssi-xmpp#27]
According to darix (in #21 ), this might happen:

15:43:51 -!- Irssi: critical Source ID 1 was not found when attempting to remove it

**Comment by simmel** [comment]
I've seen that too.

**Comment by fbettag** [comment]
i'm having this on openbsd trying to connect to jabber.ccc.de

**Comment by jtprog** [comment]
hi all! somebody have any solutions?!

**Comment by cdidier** [comment]
Fixed by https://github.com/cdidier/irssi-xmpp/commit/3e396a6a2b433ef597f42c7fd586fdef6cd92d21.
