### ISSUE TITLE
xmpp/core is ABI version 7 but Irssi is version 13, cannot load

### ISSUE THREAD

**Issue by tobiasvl** [cdidier/irssi-xmpp#33]
After upgrading from Fedora 27 to 28, irssi-xmpp no longer works:

```
/load xmpp
xmpp/core is ABI version 7 but Irssi is version 13, cannot load
Error loading module xmpp/fe: /usr/lib64/irssi/modules/libfe_xmpp.so: undefined symbol: xmpp_subscription
xmpp/core is ABI version 7 but Irssi is version 13, cannot load
```

Versions:
* irssi: irssi-1.1.1-1.fc28.src.rpm
* irssi-xmpp: irssi-xmpp-0.54-2.fc28.src.rpm

**Comment by fschlich** [comment]
a rebuild of irssi-xmpp should fix this

**Comment by tobiasvl** [comment]
OK, thanks. Reported it to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1575982
