### ISSUE TITLE
xmpppasswd

### ISSUE THREAD

**Issue by kasimiral** [cdidier/irssi-xmpp#34]
Hello, i'm using Irssi v1.0.7-1 with irssi-plugin-xmpp 0.54-2 buster (testing), how i can change my xmpp-password? With xmpppasswd? What is the syntax? thanks for reading.

**Comment by fschlich** [comment]
in `src/core/xep/registration.c` it says:

`/* SYNTAX: XMPPPASSWD -yes <old_password> <new_password> */`

**Comment by kasimiral** [comment]
Indeed. Many thanks for your help.
